name: GitHub Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: generated/overview.svg
          token: ${{ secrets.GH_README_TOKEN }}
          base: header, activity, community, repositories
          
            # Plugins
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_visibility: public
          plugin_activity_limit: 5

          plugin_achievements: no
          plugin_gists: no
          plugin_isocalendar: no

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_README_TOKEN }}

          # Save languages file
          filename: generated/languages.svg

          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_indepth: no
          plugin_languages_limit: 8
